Wait for CNV deployment before installing hco

diff --git a/dev-cluster b/dev-cluster
--- a/dev-cluster
+++ b/dev-cluster
@@ -134,6 +134,36 @@ function devcluster::install-cnv() {
 	echo "Sleep 60 seconds..."
 	sleep 60
 
+	echo "Wait for CNV deployment to be done..."
+	RETRIES=30
+	CSV=
+	for i in $(seq ${RETRIES}); do
+	  if [[ -z ${CSV} ]]; then
+	    CSV=$(oc get subscription -n openshift-cnv hco-operatorhub -o jsonpath='{.status.installedCSV}')
+	  fi
+	  if [[ -z ${CSV} ]]; then
+	    echo "Try ${i}/${RETRIES}: can't get the CSV yet. Checking again in 30 seconds"
+	    sleep 30
+	  fi
+	  if [[ $(oc get csv -n openshift-cnv ${CSV} -o jsonpath={.status.phase}) == "Succeeded" ]]; then
+	    echo "CNV is deployed"
+	    break
+	  else
+	    echo "Try ${i}/${RETRIES}: CNV is not deployed yet. Checking again in 30 seconds"
+	    sleep 30
+	  fi
+	done
+	
+	if [[ $(oc get csv -n openshift-cnv ${CSV} -o jsonpath={.status.phase}) != "Succeeded" ]]; then
+	  echo "Error: Failed to deploy CNV"
+	  echo "CSV ${CSV} YAML"
+	  oc get CSV ${CSV} -n openshift-cnv -o yaml
+	  echo
+	  echo "CSV ${CSV} Describe"
+	  oc describe CSV ${CSV} -n openshift-cnv
+	  exit 1
+	fi
+
 	echo "Deploying the OpenShift Virtualization Operator..."
 	cat  manifests/cnv/hco.yaml | kubectl apply -f -
 }
